### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ToanLyHoa** [alexandrosstergiou/progressive-action-prediction#3] opened 2023-02-28 08:20 UTC
I try to train the model with any batch size and worker but I met memory leak, how can I solve this problem?

**Comment by alexandrosstergiou** [comment] 2024-01-16 15:31
Hi @ToanLyHoa , some errors in previous versions of the code may have been caused by different torch and apex configurations of different systems when flushing the buffered memory in `model.py`. This should now be fixed in the latest commit.

**Closed as completed by alexandrosstergiou** 2024-01-16 15:31 UTC
